/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // https://docusaurus.io/docs/sidebar/multiple-sidebars
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    "intro",
    // { type: "autogenerated", dirName: "." },
    {
      type: "category",
      label: "Tutorial - Community",
      items: [{ type: "autogenerated", dirName: "02-community" }],
    },
    {
      type: "category",
      label: "Tutorial - Members",
      items: [{ type: "autogenerated", dirName: "03-members" }],
    },
    {
      type: "category",
      label: "Tutorial - Administrators",
      items: [{ type: "autogenerated", dirName: "04-administrators" }],
    },
    {
      type: "category",
      label: "Tutorial - Editors",
      items: [{ type: "autogenerated", dirName: "05-editors" }],
    },
    {
      type: "category",
      label: "Get Involved",
      items: [{ type: "autogenerated", dirName: "06-get-involved" }],
    },
    {
      type: "category",
      label: "Tutorial - Volunteers",
      items: [{ type: "autogenerated", dirName: "07-volunteers" }],
    },
    "developers"
  ],

  // But you can create a sidebar manually
  /*
  
  
  
  */
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
